site_name: Nazuna
theme:
  name: material
  palette:
    primary: white
extra_css:
  - custom.css
nav:
  - Home: index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CookieBox26/nazuna
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            heading_level: 3
            show_root_heading: true
            docstring_section_style: list
            show_source: false
            show_bases: true
markdown_extensions:
  - pymdownx.superfences
