site_name: Nazuna
theme:
  name: material
  palette:
    primary: white
extra_css:
  - custom.css
nav:
  - Home: index.md
  - Key Ideas: key_ideas.md
  - About Config File: config.md
  - Reference: reference.md
  - Reference (Models): reference_models.md
  - Reference (Diagnoser): reference_diagnoser.md
  - Reference (Task Runners): reference_task_runners.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CookieBox26/nazuna
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            heading_level: 3
            show_root_heading: true
            docstring_section_style: list
            show_source: false
            show_bases: true
            filters: []
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
