out_dir = "./out/jma_daily_train_savd"
exist_ok = true

[data]
path = [ "jma", "weather_japan_daily_2025-01-01_2025-12-31_2_blocks.csv",]
colname_timestamp = "date"
seq_len = 28
pred_len = 7
white_list = [ "temp_avg_nagoya", "temp_avg_fukuoka",]

[[tasks]]
task_type = "eval"
name = "Eval SimpleAverage"
data_range_eval = [ 0.8, 1.0,]
criterion_cls_path = "nazuna.criteria.MAE"
criterion_params = { n_channel = 2, pred_len = 7, tolerance = 0.05 }
model_cls_path = "nazuna.models.simple_average.SimpleAverage"
model_params = { seq_len = 28, pred_len = 7, period_len = 7 }

[[tasks]]
task_type = "train"
name = "Train SimpleAverageVariableDecay"
data_range_eval = [ 0.8, 1.0,]
criterion_cls_path = "nazuna.criteria.MAE"
criterion_params = { n_channel = 2, pred_len = 7, tolerance = 0.05 }
model_cls_path = "nazuna.models.simple_average.SimpleAverageVariableDecay"
model_params = { seq_len = 28, pred_len = 7, period_len = 7 }
data_range_train = [ 0.0, 0.8,]
batch_sampler_cls_path = "nazuna.batch_sampler.BatchSamplerShuffle"
batch_sampler_params = { batch_size = 16 }
optimizer_cls_path = "torch.optim.Adam"
optimizer_params = { lr = 0.05 }
lr_scheduler_cls_path = "torch.optim.lr_scheduler.CosineAnnealingLR"
lr_scheduler_params = { T_max = 5 }
n_epoch = 10

[[tasks]]
task_type = "eval"
name = "Eval SimpleAverageVariableDecay"
data_range_eval = [ 0.8, 1.0,]
criterion_cls_path = "nazuna.criteria.MAE"
criterion_params = { n_channel = 2, pred_len = 7, tolerance = 0.05 }
model_cls_path = "nazuna.models.simple_average.SimpleAverageVariableDecay"
model_params = { seq_len = 28, pred_len = 7, period_len = 7 }
model_state = { task_name = "Train SimpleAverageVariableDecay" }
