out_dir = "./out/jma_hourly_3m_diag"
exist_ok = true

[data]
path = [ "jma", "weather_japan_hourly_2025-09-01_2025-12-31_27_blocks.csv",]
colname_timestamp = "timestamp"
seq_len = 96
pred_len = 24
white_list = [ "temp_fukuoka", "temp_osaka", "temp_tokyo", "temp_sendai",]

[[tasks]]
task_type = "diag"
name = "Diagnostics"
data_range_diag = [ 0.0, 0.2,]
period = 24
